sudo: required
services:
  - docker

before_install:
  - docker build -t DineshTraining2020/nodejsTesting -f Dockerfile.dev .

script:
  - docker run -t dineshkallu/nodejstesting npm run test -- --coverage
